admin_module/estate/urls.py
from django.urls import path


from .views import (EstateListView, EstateDeleteView, EstateCreateView, EstatePropertyCreateView, EstateDetailView,
                    EstateUpdateView, EstatePropertyListView, EstatePropertyDeleteView, EstatePropertyUpdateView,
                    EstateRegionListView, EstateRegionDeleteView, EstateRegionCreateView, EstateRegionUpdateView,
                    EstateImageDeleteView, EstateImageCreateView)

urlpatterns = [
    path('', EstateListView.as_view(), name='estates-list'),
    path('<pk>/detail/', EstateDetailView.as_view(), name='estates-detail'),
    path('<pk>/delete/', EstateDeleteView.as_view(), name='estates-delete'),
    path('<pk>/edit/', EstateUpdateView.as_view(), name='estates-update'),
    path('new/', EstateCreateView.as_view(), name='create-estate'),
    
    path('properties/', EstatePropertyListView.as_view(), name='estate-property-list'),
    path('properties/new', EstatePropertyCreateView.as_view(), name='estate-property-create'),
    path('properties/<pk>/delete/', EstatePropertyDeleteView.as_view(), name='estate-property-delete'),
    path('properties/<pk>/update/', EstatePropertyUpdateView.as_view(), name='estate-property-update'),

    path('regions/', EstateRegionListView.as_view(), name='estate-region-list'),
    path('regions/<pk>/delete/', EstateRegionDeleteView.as_view(), name='estate-region-delete'),
    path('regions/new', EstateRegionCreateView.as_view(), name='estate-region-create'),
    path('regions/<pk>/update/', EstateRegionUpdateView.as_view(), name='estate-region-update'),

    path('<estate_id>/images/<pk>/delete/', EstateImageDeleteView.as_view(), name='estate-image-delete'),
    path('<estate_id>/images/new/', EstateImageCreateView.as_view(), name='estate-image-create'),


]

admin_module/urls.py
from django.urls import path, include

from .views import (dashboard)
from better_home_api import settings
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('logout/', LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='logout-admin'),
    path('users/', include('admin_module.user.urls'), name='admin-user'),
    path('estates/', include('admin_module.estate.urls'), name='admin-estate'),
    path('user-contacts/', include('admin_module.user_contact.urls'), name='admin-user-contact'),
]

admin_module/user/urls.py
from django.urls import path

from .views import (AllUsersListView, CreateUserView, ConsultantUsersListView,
                    UserUpdateView, ChangeUserPasswordUpdateView, DeleteUserView, UserDetailView,
                    export_user_to_xlsx, move_consultant_estates_to_other_consultant)


urlpatterns = [
    path('', AllUsersListView.as_view(), name='users-list'),
    path('export-excel', export_user_to_xlsx, name='export-user-to-xlsx'),
    path('consultants', ConsultantUsersListView.as_view(), name='consultant-users-list'),
    path('<int:pk>/detail', UserDetailView.as_view(), name='user-detail'),
    path('<int:pk>/update', UserUpdateView.as_view(), name='user-update'),
    path('<int:pk>/delete', DeleteUserView.as_view(), name='user-delete'),
    path('<int:pk>/change-password', ChangeUserPasswordUpdateView.as_view(), name='user-change-password'),
    path('<int:pk>/move-estate', move_consultant_estates_to_other_consultant, name='move-consultant-estates-to-other-consultant'),
    path('new', CreateUserView.as_view(), name='create-user'),
]

better_home_api/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.decorators import login_required

from decorator_include import decorator_include

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from admin_module.views import login_admin

schema_view = get_schema_view(
   openapi.Info(
      title="Better Home APIs",
      default_version='v1',
      description="Better home API",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="general.sina.amini.20@gmail.com"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('admin/', decorator_include(login_required, include('admin_module.urls')), name='admin'),
    path('admin/login/', login_admin, name='login-admin'),
    path('api/v1/', include('api_v1_module.urls'), name='api-v1'),
    path('docs', schema_view.with_ui('redoc', cache_timeout=0), name='docs'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

estate_module/models.py
from datetime import datetime, timedelta


import static_variables

from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.templatetags.static import static

from PIL import Image

from base_model_module.models import BaseModel
from .managers import EstateManager

User = get_user_model()


class EstateProperty(BaseModel):
    title = models.CharField(verbose_name='عنوان', max_length=100)
    icon = models.ImageField(upload_to=static_variables.ESTATE_PROPERTY_IMAGE_UPLOAD_PATH, verbose_name='آیکن')
    
    def __str__(self):
        return f'{self.title}'
    
    class Meta:
        verbose_name = 'ویژگی ملک'
        verbose_name_plural = 'ویژگی های ملک'

# TODO: maybe category model added in future
# class EstateCategory(BaseModel):
#     parent = models.ForeignKey('self', related_name='children', on_delete=models.CASCADE, blank=True, null=True, verbose_name='والد')
#     title = models.CharField(max_length=100, verbose_name='عنوان')
#     slug = models.SlugField(unique=True, null=False, editable=False)

#     def __str__(self):
#         return self.title

#     class Meta:
#         #enforcing that there can not be two categories under a parent with same slug
#         unique_together = ('slug', 'parent',)
#         verbose_name = "دسته بندی ملک"
#         verbose_name_plural = "دسته بندی های ملک"
    

class EstateRegion(BaseModel):
    title = models.CharField(verbose_name='عنوان', max_length=300)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "منطقه"
        verbose_name_plural = "منطقه ها"

    
class EstateImage(BaseModel):
    image = models.ImageField(upload_to=static_variables.ESTATE_IMAGE_UPLOAD_PATH, verbose_name='تصویر ملک')
    
    def __str__(self):
        return f'{self.image}'
    
    class Meta:
        verbose_name = 'تصویر ملک'
        verbose_name_plural = 'تصویر های ملک'

    #creating watermark for photo
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        src_path = self.image.path.split('better_home_api')
        # opacity value
        TRANSPARENCY = 100
        
        # original image
        photo = Image.open(self.image.path)
        width, height = photo.size

        # open watermark image
        watermark = Image.open(src_path[0] + 'better_home_api' + static('image-watermark.png'))
        watermark_width, watermark_height = watermark.size 

        # resize watermark image
        watermark = watermark.resize((int(watermark_width / 2), int(watermark_height / 2)))
        watermark_width, watermark_height = watermark.size 

        # set position of watermark
        margin = 10
        x = width - watermark_width - margin
        y = height - watermark_height - margin

        # change opacity of watermark
        paste_mask = watermark.split()[3].point(lambda i: i * TRANSPARENCY / 100.)
        photo.paste(watermark, (x, y), mask=paste_mask)
        photo.save(self.image.path)


class Estate(BaseModel):
    title = models.CharField(verbose_name='عنوان', max_length=300)
    description = models.TextField(verbose_name='توضیحات', null=True, blank=True)
    consultant = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='مشاور')
    address = models.TextField(verbose_name='آدرس')
    latitude = models.FloatField(verbose_name='طول جغرافیایی')
    longitude = models.FloatField(verbose_name='عرض جغرافیایی')
    number_of_rooms = models.PositiveIntegerField(verbose_name='تعداد اتاق ها')
    floor = models.PositiveIntegerField(verbose_name='طبقه')
    estate_properties = models.ManyToManyField(EstateProperty, verbose_name='ویژگی ها', blank=True)
    meterage = models.PositiveIntegerField(verbose_name='متراژ')
    category = models.CharField(choices=static_variables.AD_CATEGORY_CHOICES, max_length=15,
                                verbose_name='دسته بندی', null=True, blank=True)
    is_special = models.BooleanField(verbose_name='آگهی ویژه', default=False)
    images = models.ManyToManyField(EstateImage, verbose_name='تصاویر', blank=True)
    price = models.BigIntegerField(verbose_name='قیمت')
    deposit = models.BigIntegerField(verbose_name='ودیعه', null=True, blank=True)
    ad_type = models.CharField(choices=static_variables.AD_TYPE_CHOICES, max_length=10, verbose_name='نوع آگهی')
    is_ladder = models.BooleanField(default=False, verbose_name='نردبون')
    is_publish = models.BooleanField(default=False, verbose_name='انتشار نهایی')
    is_convertible = models.BooleanField(default=False, verbose_name='قابل تغییر بودن')
    price_converted = models.PositiveBigIntegerField(verbose_name='قیمت تغییر یافته', null=True, blank=True)
    deposit_converted = models.PositiveBigIntegerField(verbose_name='ودیعه تغییر یافته', null=True, blank=True)
    last_ladder_updated_time = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اپدیت نردبون', null=True, blank=True)
    build_date = models.PositiveIntegerField(verbose_name='سال ساخت', null=True, blank=True)
    fav_of_users = models.ManyToManyField(User, verbose_name='مورد علاقه', blank=True, related_name='fav_of_users')
    region = models.ForeignKey(EstateRegion, on_delete=models.CASCADE, null=True, blank=True, verbose_name='منطقه')
    
    objects = EstateManager()

    def __str__(self):
        return f'{self.consultant.username} - {self.title}'

    class Meta:
        verbose_name = 'ملک'
        verbose_name_plural = 'ملک ها'


@receiver(pre_save, sender=Estate)
def set_estate_expire_date(sender, instance, *args, **kwargs):
    # set expire_date when instance created
    if instance.id is None:
        instance.expire_date = datetime.now() + timedelta(days=30)

admin_module/estate/views.py
from django.views.generic import ListView, DeleteView, CreateView, UpdateView, DetailView

from django.urls import reverse_lazy
from django.shortcuts import redirect

from estate_module.models import Estate, EstateProperty, EstateRegion, EstateImage

from .forms import CreateEstateForm, UpdateEstateForm, CreateEstatePropertyForm, UpdateEstatePropertyForm, CreateUpdateEstateRegionForm, CreateUpdateEstateImageForm

class EstateListView(ListView):
    model = Estate
    paginate_by = 30
    template_name = 'estate/estate_list.html'


    def get_queryset(self):
        search = self.request.GET.get('search', '')
        object_list = self.model.objects.all().order_by('-id')
        if search:
            object_list = self.model.objects.filter(title__icontains=search).distinct().order_by('-id')
        return object_list


class EstateDeleteView(DeleteView):
    model = Estate
    template_name = 'estate/estate_confirm_delete.html'
    success_url = reverse_lazy('estates-list')
    


class EstateDetailView(DetailView):
    model = Estate
    template_name = 'estate/estate_detail.html'
    

class EstateCreateView(CreateView):
    model = Estate
    form_class = CreateEstateForm
    template_name = 'estate/estate_form.html'
    success_url = reverse_lazy('estates-list')


class EstateUpdateView(UpdateView):
    model = Estate
    form_class = UpdateEstateForm
    template_name = 'estate/estate_form.html'
    success_url = reverse_lazy('estates-list')


class EstatePropertyListView(ListView):
    model = EstateProperty
    template_name = 'estate/properties/estate_property_list.html'
    paginate_by = 30


    def get_queryset(self):
        search = self.request.GET.get('search', '')
        object_list = self.model.objects.all().order_by('-id')
        if search:
            object_list = self.model.objects.filter(title__icontains=search).distinct().order_by('-id')
        return object_list


class EstatePropertyDeleteView(DeleteView):
    model = EstateProperty
    template_name = 'estate/properties/estate_property_confirm_delete.html'
    success_url = reverse_lazy('estate-property-list')


class EstatePropertyCreateView(CreateView):
    model = EstateProperty
    form_class = CreateEstatePropertyForm
    template_name = 'estate/properties/estate_property_form.html'
    success_url = reverse_lazy('estate-property-list')



class EstatePropertyUpdateView(UpdateView):
    model = EstateProperty
    form_class = UpdateEstatePropertyForm
    template_name = 'estate/properties/estate_property_form.html'
    success_url = reverse_lazy('estate-property-list')


class EstateRegionListView(ListView):
    model = EstateRegion
    paginate_by = 30
    template_name = 'estate/region/estate_region_list.html'


    def get_queryset(self):
        search = self.request.GET.get('search', '')
        object_list = self.model.objects.all().order_by('-id')
        if search:
            object_list = self.model.objects.filter(title__icontains=search).distinct().order_by('-id')
        return object_list


class EstateRegionDeleteView(DeleteView):
    model = EstateRegion
    template_name = 'estate/region/estate_region_confirm_delete.html'
    success_url = reverse_lazy('estate-region-list')


class EstateRegionCreateView(CreateView):
    model = EstateRegion
    form_class = CreateUpdateEstateRegionForm
    template_name = 'estate/region/estate_region_form.html'
    success_url = reverse_lazy('estate-region-list')



class EstateRegionUpdateView(UpdateView):
    model = EstateRegion
    form_class = CreateUpdateEstateRegionForm
    template_name = 'estate/region/estate_region_form.html'
    success_url = reverse_lazy('estate-region-list')


class EstateImageDeleteView(DeleteView):
    model = EstateImage
    template_name = 'estate/image/estate_image_confirm_delete.html'
    
    def get_success_url(self) -> str:
        estate_id = self.kwargs['estate_id']
        return reverse_lazy('estates-detail', args=(estate_id,))

class EstateImageCreateView(CreateView):
    model = EstateImage
    form_class = CreateUpdateEstateImageForm
    template_name = 'estate/image/estate_image_form.html'

    def form_valid(self, form):
        estate_id = self.kwargs['estate_id']
        obj = form.save(commit=False)
        obj.save()
        selected_estate = Estate.objects.filter(pk=estate_id).first()
        selected_estate.images.add(obj)
        selected_estate.save()
        return redirect(reverse_lazy('estates-detail', args=(estate_id,)))

admin_module/user_contact/views.py
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import DeleteView, CreateView

from user_contact_module.models import UserContact

from .forms import CreateUserContactForm

class DeleteUserContactView(DeleteView):
    model = UserContact
    template_name = 'user_contact/user_contact_confirm_delete.html'
    success_url = reverse_lazy('users-list')


class CreateUserContactView(CreateView):
    model = UserContact
    form_class = CreateUserContactForm
    template_name = 'user_contact/user_contact_form.html'

    def form_valid(self, form):
        consultant_id = self.kwargs['consultant_id']
        
        obj = form.save(commit=False)
        obj.consultant_id = consultant_id
        obj.save()
        return redirect(reverse('user-detail', args=(consultant_id,)))

admin_module/views.py
import psutil
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import get_user_model, authenticate, login, logout

from estate_module.models import Estate


User = get_user_model()


def login_admin(request):
    if request.user.is_authenticated:
        return redirect(reverse('dashboard'))
    if request.method == 'POST':
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = authenticate(request, username=username, password=password)
        if user is not None and user.is_staff:
            login(request, user)
            return redirect(reverse('dashboard'))
    return render(request, 'login.html')


def dashboard(request):
    all_users = User.objects.all()
    all_users_count = all_users.count()
    all_consultants_count = all_users.filter(is_consultant=True).count()
    all_estates_ads = Estate.objects.all()
    memory_percent_usage = psutil.virtual_memory()[2]
    cpu_percent_usage = psutil.cpu_percent()
    latest_users = all_users.order_by('-id')[:10]
    latest_estates_ads = all_estates_ads.order_by('-id')[:10]

    context = {
        'all_users_count': all_users_count,
        'latest_users': latest_users,
        'all_consultants_count': all_consultants_count,
        'all_estates_ads': all_estates_ads.count(),
        'memory_percent_usage': memory_percent_usage,
        'cpu_percent_usage': cpu_percent_usage,
        'latest_estates_ads': latest_estates_ads,
    }
    return render(request, 'dashboard.html', context)


admin_module/templates/estate/estate_confirm_delete.html
{% extends 'shared/main_layout_admin.html' %}

{% block content_header %}
<h1>تایید حذف</h1>
{% endblock %}

{% block content %}
<section class="content">
    <div class="row">
        <div class="col-12">
            <form method="post">{% csrf_token %}
                <div class="alert alert-warning">آیا از حذف آگهی "{{ object.title }}" مطمئن هستید؟</div>
                <input type="submit" value="بله, حذف کن" class="btn btn-danger">
                <a class="btn btn-default" href="{% url 'estates-list' %}">انصراف</a>
            </form>
        </div>
    </div>
</section>
{% endblock %}

admin_module/templates/estate/estate_detail.html
{% extends 'shared/main_layout_admin.html' %}
{% load static %}
{% load humanize %}

{% block content %}
<section class="content">

  <div class="row">
    <div class="col-md-6">

      <!-- Profile Image -->
      <div class="box box-primary">
        <div class="box-body box-profile">
          <h3 class="profile-username text-center">{{ object.consultant }}</h3>

          <p class="text-muted text-center">{{ object.description }}</p>

          <ul class="list-group list-group-unbordered">
            <li class="list-group-item">
              <b>عنوان</b> <a class="pull-left">{{ object.title }}</a>
            </li>
            <li class="list-group-item">
              <b>آدرس</b> <a class="pull-left">{{ object.address }}</a>
            </li>
            <li class="list-group-item">
              <b>محله</b> <a class="pull-left">{{ object.region }}</a>
            </li>
            <li class="list-group-item">
              <b>مختصات</b> <a class="pull-left">{{ object.latitude }} - {{ object.longitude }}</a>
            </li>

            <li class="list-group-item">
                <b>نوع آگهی</b> <a class="pull-left">{{ object.get_ad_type_display }}</a>
            </li>

            <li class="list-group-item">
                <b>نوع ملک</b> <a class="pull-left">{{ object.get_category_display }}</a>
            </li>

            
            <li class="list-group-item">
                <b>تعداد اتاق</b> <a class="pull-left">{{ object.number_of_rooms }}</a>
            </li>

            <li class="list-group-item">
                <b>طبقه</b> <a class="pull-left">{{ object.floor }}</a>
            </li>


            <li class="list-group-item">
                <b>متراژ</b> <a class="pull-left">{{ object.meterage }}</a>
            </li>


            <li class="list-group-item">
                <b>آگهی ویژه</b> <a class="pull-left">{{ object.is_special }}</a>
            </li>


            <li class="list-group-item">
                <b>آگهی نردبون</b> <a class="pull-left">{{ object.is_ladder }}</a>
            </li>


            <li class="list-group-item">
                <b>قیمت</b> <a class="pull-left">{{ object.price }}</a>
            </li>


            <li class="list-group-item">
              <b>قابل تغییر</b> <a class="pull-left">{{ object.is_convertible }}</a>
          </li>

            <li class="list-group-item">
              <b>قیمت تغییر یافته</b> <a class="pull-left">{{ object.price_converted }}</a>
            </li>

            <li class="list-group-item">
                <b>ودیعه</b> <a class="pull-left">{{ object.deposit }}</a>
            </li>


            <li class="list-group-item">
              <b>ودیعه تغییر یافته</b> <a class="pull-left">{{ object.deposit_converted }}</a>
          </li>

        </ul>

          <a href="{% url 'estates-update' object.pk %}" class="btn btn-primary btn-block"><b>ویرایش اطلاعات</b></a>
          <a href="{% url 'estates-delete' object.pk %}" class="btn btn-danger btn-block"><b>حذف اطلاعات</b></a>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
    </div>
    <!-- /.col -->
    <div class="col-md-6">
      <div class="nav-tabs-custom">
        <ul class="nav nav-tabs">
          <li class="active"><a href="#favs" data-toggle="tab">مورد علاقه ها ({{ object.fav_of_users.all.count }})</a></li>
          <li><a href="#properties" data-toggle="tab">ویژگی ({{object.estate_properties.all.count}})</a></li>
          <li><a href="#images" data-toggle="tab">تصاویر ({{ object.images.all.count }})</a></li>
        </ul>
        <div class="tab-content">
          <div class="active tab-pane" id="favs">

            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding mt-5">
              <table class="table table-hover">
                <tbody>
                  <tr>
                    <th>شناسه</th>
                    <th>نام کاربری</th>
                    <th>شماره تلفن</th>
                    <th>مشاور</th>
                    <th>ادمین</th>
                    <th>مشاور</th>
                  </tr>
                  {% for fav_of_user in object.fav_of_users.all %}
                  <tr>
                    <td>{{ fav_of_user.pk }}</td>
                    <td><a href="{% url 'user-detail' fav_of_user.pk %}">{{ fav_of_user.username }}</a></td>
                    <td>{{ fav_of_user.phone_number }}</td>
                    <td>{{ estate.consultant }}
                    <td>
                      {% if fav_of_user.is_superuser and fav_of_user.is_staff %}
                      <span class="label label-success">ادمین</span>
                      {% else %}
                      <span class="label label-warning">عادی</span>
                      {% endif %}
                    </td>
                    <td>
                      {% if fav_of_user.is_consultant %}
                      <span class="label label-success">مشاور</span>
                      {% else %}
                      <span class="label label-warning">عادی</span>
                      {% endif %}
                    </td>
                  </tr>
                  {% empty %}
                  <h4 class="text-center">پیدا نشد</h4>
                  {% endfor %}
                </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <div class="tab-pane" id="properties">

            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding mt-5">
              <table class="table table-hover">
                <tbody>
                  <tr>
                    <th>شناسه</th>
                    <th>عنوان</th>
                  </tr>
                  {% for property in object.estate_properties.all %}
                  <tr>
                    <td>{{ property.pk }}</td>
                    <td><a href="{% url 'estate-property-update' property.pk %}">{{ property.title }}</a></td>
                  </tr>
                  {% empty %}
                  <h4 class="text-center">پیدا نشد</h4>
                  {% endfor %}
                </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <div class="tab-pane" id="images">

            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding mt-5">
              <a class="btn btn-primary" href="{% url 'estate-image-create' object.pk %}">اضافه کردن تصویر</a>
              <table class="table table-hover" style="margin-top: 5px;">
                <tbody>
                  <tr>
                    <th>شناسه</th>
                    <th>لینک</th>
                    <th>دستور</th>
                  </tr>
                  {% for image in object.images.all %}
                  <tr>
                    <td>{{ image.pk }}</td>
                    <td><a href="{{ image.image.url }}">برای مشاهده کلیک کنید</a></td>
                    <td>
                      <a class="btn btn-danger" href="{% url 'estate-image-delete' object.pk image.pk %}">حذف کردن</a>
                    </td>
                  </tr>
                  {% empty %}
                  <h4 class="text-center">پیدا نشد</h4>
                  {% endfor %}
                </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
        </div>
        <!-- /.tab-content -->
      </div>
      <!-- /.nav-tabs-custom -->
    </div>
    <!-- /.col -->
  </div>
  <!-- /.row -->

</section>
{% endblock %}

admin_module/templates/estate/estate_form.html
{% extends 'shared/main_layout_admin.html' %}

{% block content_header %}
<h1>افزودن ملک</h1>
{% endblock %}

{% block content %}
<section class="content">
    <div class="row">
        <div class="col-12">
            <div class="box box-primary">
              <div class="box-header with-border">
                <h3 class="box-title">مشخصات زیر را وارد کنید</h3>
              </div>
              <!-- /.box-header -->
              <!-- form start -->
              <form class="form-horizontal" method="POST">
                {% csrf_token %}
                
                <div class="box-body">
                    <div class="row">
                        {% for field in form %}
                        <div class="col-sm-12 col-md-6">
                            <label  for="{{ field.id_for_label }}" class="control-label">{{ field.label }}</label>  
                            {{ field }}
                            {{ field.errors }}
                        </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="box-footer">
                    <button type="submit" class="btn btn-info btn-block">ذخیره</button>
                    <a href="{{request.META.HTTP_REFERER}}" class="btn btn-danger btn-block">انصراف</a>
                </div>
              </form>
            </div>
          </div>
    </div>
</section>
{% endblock %}